### PR TITLE
Server Side Rendering

### PR DESCRIPTION
**Pull request by rizkiandrianto**
Do you have suggestion to use in server rendering?
I got `window is not defined` when rendering from server.

### CODE REVIEW

**Comment by rizkiandrianto** [comment]
I think maybe you might take a look my PR. I've test it in Server side, but not in client side yet 😅 
Could you please maybe help me to test in client side.

**Comment by andreaswilli** [comment]
Thanks for the PR. 
Basically it works on client side as well, but `<style dangerouslySetInnerHTML={{ __html: style }} />` is adding the styles directly to the component and thus overriding possible custom styles from the `head` 😞

**Comment by rizkiandrianto** [comment]
Well I use your amazing works, at least with my patch it will works in my case first 😅 
Maybe you can help to make it more tidy 😋 

Or maybe manually extract scss into css and let the user import it self will be okay like **[nprogress](https://github.com/rstacruz/nprogress)** do 😉

**Comment by andreaswilli** [comment]
Styles seem to be fine now.

**Comment by andreaswilli** [comment]
Merged and released as `v0.1.4`.

**Comment by Mazenebeid** [comment]
Hi

How do u get the value from this compoment. I am sorry if this is a basic question but I am strgguling to use it

**Comment by andreaswilli** [comment]
Hi, thanks for using my component.

The `props.input.onChange` callback will be called on every change of the value.
This means you can get it like this:
```
<VerificationInput input={{
    onChange: value => console.log(value),
}} />
```
Then you can put it in your state or whatever.
Sorry if this was a bit confusing.

**Comment by MazEbeid** [comment]
Hi Andreas that is great thanks for your help. No I am fairly new to this and using Custom components still confuses me.

Cheers for the help

**Comment by andreaswilli** [comment]
Great, I'm always happy to help.

**Pull request merged**
