### PR TITLE
Add filled character class

### PR DESCRIPTION
**Pull request by priidikvaikla**
Add way to style filled characters

### CODE REVIEW

**Comment by priidikvaikla** [comment]
Hey @andreaswilli! I would like to add different styles to the characters that have been filled, so placeholders could be gray for example and filled chars black. What do you think of this approach?

**Comment by andreaswilli** [comment]
Thanks for the PR @priidikvaikla! I like your proposal, since this could also improve the [cursor recipe](https://andreaswilli.github.io/react-verification-input/styling#with-cursor-caret) (which currently does not work if we use a placeholder).

Implementation looks good, please add/update unit tests. Afterwards, I can update the cursor docs.

**Comment by priidikvaikla** [comment]
Added tests

**Review by andreaswilli — APPROVED** [review]
Thanks for adding tests

**Comment by andreaswilli** [comment]
Published `v4.1.0`.

**Pull request merged**
