### PR TITLE
feat: implement password mode

### PR DESCRIPTION
**Pull request by reinos**
This MR implement a `PasswordMode` so it will masked the user input on screen.

### CODE REVIEW

**Review by andreaswilli — CHANGES_REQUESTED** [review]
Thanks for contributing!

I'm happy to accept this, but I think we also need to set `type="password"` on the `input` element in order to get the default behavior of password inputs (e.g. not being announced by screen readers).

**Comment by reinos** [comment]
Good point, updated the branch (and also the docs)

**Review by andreaswilli — APPROVED** [review]
Thanks, now it looks good. I'll merge it and create a new release.

**Comment by andreaswilli** [comment]
`v3.2.0` released

**Pull request merged**
